#!/usr/bin/env fish
wlr-randr --output eDP-1 --pos 0,0
# wlr-randr --output eDP-1 --scale 1.01
# wlr-randr --output eDP-1 --scale 1.02
# wlr-randr --output eDP-1 --scale 1.03
# wlr-randr --output eDP-1 --scale 1.04
# wlr-randr --output eDP-1 --scale 1.05
# wlr-randr --output eDP-1 --scale 1.06
# wlr-randr --output eDP-1 --scale 1.07
# wlr-randr --output eDP-1 --scale 1.08
# wlr-randr --output eDP-1 --scale 1.09
# wlr-randr --output eDP-1 --scale 1.10
# wlr-randr --output eDP-1 --scale 1.11
# wlr-randr --output eDP-1 --scale 1.12
# wlr-randr --output eDP-1 --scale 1.13
# wlr-randr --output eDP-1 --scale 1.14
# wlr-randr --output eDP-1 --scale 1.15
# wlr-randr --output eDP-1 --scale 1.16
# wlr-randr --output eDP-1 --scale 1.17
# wlr-randr --output eDP-1 --scale 1.18
# wlr-randr --output eDP-1 --scale 1.19
# wlr-randr --output eDP-1 --scale 1.20
# wlr-randr --output eDP-1 --scale 1.21
# wlr-randr --output eDP-1 --scale 1.22
# wlr-randr --output eDP-1 --scale 1.23
# wlr-randr --output eDP-1 --scale 1.24
# wlr-randr --output eDP-1 --scale 1.25
# wlr-randr --output eDP-1 --scale 1.26
# wlr-randr --output eDP-1 --scale 1.27
# wlr-randr --output eDP-1 --scale 1.28
# wlr-randr --output eDP-1 --scale 1.29
# wlr-randr --output eDP-1 --scale 1.30
# wlr-randr --output eDP-1 --scale 1.31
# wlr-randr --output eDP-1 --scale 1.32
# wlr-randr --output eDP-1 --scale 1.33
# wlr-randr --output eDP-1 --scale 1.34
# wlr-randr --output eDP-1 --scale 1.35
# wlr-randr --output eDP-1 --scale 1.36
# wlr-randr --output eDP-1 --scale 1.37
# wlr-randr --output eDP-1 --scale 1.38
# wlr-randr --output eDP-1 --scale 1.39
# wlr-randr --output eDP-1 --scale 1.40
# wlr-randr --output eDP-1 --scale 1.41
# wlr-randr --output eDP-1 --scale 1.42
# wlr-randr --output eDP-1 --scale 1.43
# wlr-randr --output eDP-1 --scale 1.44
# wlr-randr --output eDP-1 --scale 1.45
# wlr-randr --output eDP-1 --scale 1.46
# wlr-randr --output eDP-1 --scale 1.47
# wlr-randr --output eDP-1 --scale 1.48
# wlr-randr --output eDP-1 --scale 1.49
# wlr-randr --output eDP-1 --scale 1.50
# wlr-randr --output eDP-1 --scale 1.51
# wlr-randr --output eDP-1 --scale 1.52
# wlr-randr --output eDP-1 --scale 1.53
# wlr-randr --output eDP-1 --scale 1.54
# wlr-randr --output eDP-1 --scale 1.55
# wlr-randr --output eDP-1 --scale 1.56
# wlr-randr --output eDP-1 --scale 1.57
# wlr-randr --output eDP-1 --scale 1.58
# wlr-randr --output eDP-1 --scale 1.59
# wlr-randr --output eDP-1 --scale 1.60
# wlr-randr --output eDP-1 --scale 1.61
# wlr-randr --output eDP-1 --scale 1.62
# wlr-randr --output eDP-1 --scale 1.63
# wlr-randr --output eDP-1 --scale 1.64
# wlr-randr --output eDP-1 --scale 1.65
# wlr-randr --output eDP-1 --scale 1.66
# wlr-randr --output eDP-1 --scale 1.67
# wlr-randr --output eDP-1 --scale 1.68
# wlr-randr --output eDP-1 --scale 1.69
# wlr-randr --output eDP-1 --scale 1.70
# wlr-randr --output eDP-1 --scale 1.71
# wlr-randr --output eDP-1 --scale 1.72
# wlr-randr --output eDP-1 --scale 1.73
# wlr-randr --output eDP-1 --scale 1.74
# wlr-randr --output eDP-1 --scale 1.75
# wlr-randr --output eDP-1 --scale 1.76
# wlr-randr --output eDP-1 --scale 1.77
# wlr-randr --output eDP-1 --scale 1.78
# wlr-randr --output eDP-1 --scale 1.79
# wlr-randr --output eDP-1 --scale 1.80
# wlr-randr --output eDP-1 --scale 1.81
# wlr-randr --output eDP-1 --scale 1.82
# wlr-randr --output eDP-1 --scale 1.83
# wlr-randr --output eDP-1 --scale 1.84
# wlr-randr --output eDP-1 --scale 1.85
# wlr-randr --output eDP-1 --scale 1.86
# wlr-randr --output eDP-1 --scale 1.87
# wlr-randr --output eDP-1 --scale 1.88
# wlr-randr --output eDP-1 --scale 1.89
# wlr-randr --output eDP-1 --scale 1.90
# wlr-randr --output eDP-1 --scale 1.91
