# Place this in ~/.config/river/planarwm.conf

window {
  force_ssd = true
}
bindings {
  none.XF86AudioMute = "shell pactl set-sink-mute @DEFAULT_SINK@ toggle"
  none.XF86AudioLowerVolume = "shell pactl set-sink-volume @DEFAULT_SINK@ -3%"
  none.XF86AudioRaiseVolume = "shell pactl set-sink-volume @DEFAULT_SINK@ +3%"
  none.XF86AudioMicMute = "shell pactl set-source-mute @DEFAULT_SOURCE@ toggle"
  none.XF86MonBrightnessDown = "shell brightnessctl set 5%-"
  none.XF86MonBrightnessUp = "shell brightnessctl set 5%+"
  none.Print = "shell grim -g \"$(slurp)\" - | wl-copy"
  shift.Print = "shell filename=~/Pictures/Screenshots/$(date +\"%F_%Hh%Mm%Ss\").png && grim \"$filename\" && wl-copy < \"$filename\""
  alt.Print = "shell notify-send works"
  alt.j = "next_slide"
  alt.k = "prev_slide"
  alt.h = "prev_window"
  alt.l = "next_window"
  alt.n = "cycle_tiling"
  alt.t = "spawn foot"
  alt.r = "spawn wmenu-run -bip(｡•̀ᴗ-)✧"
  alt.b = "spawn firefox"
  alt-shift.b = "spawn firefox --private-window"
  alt.f = "maximize"
  alt-shift.f = "center_focused"
  alt.grave = "close"
  alt.space = "spawn qs ipc call panel toggle"
  alt.0 = "shell ~/.config/scripts/randwall.sh"
  alt.m = "shell swaylock -f -c 4e6f6f"
  alt-shift.m = "exit"
  ctrl-alt-shift.m = "shell systemctl poweroff"
  # For 1920x1080 at 1.5x, I have 1280x720
  # alt.q = "view 0     0"
  # alt.w = "view 0     720"
  # alt.e = "view 0     1440"
  # alt.a = "view 0     2160"
  # alt.s = "view 0     2880"
  # alt.d = "view 0     3600"
  # alt.i = "view 0     4320"
  # alt.o = "view 0     5040"
  # alt.p = "view 0     5760"
}

startup = [
  "dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=planarwm"
  "kanshi"
  "dunst"
  "qs"
  "~/.config/scripts/randwall.sh"
  "swayidle -w timeout 600 'swaylock -f -c 4E6F6F' timeout 900 'systemctl hybrid-sleep' before-sleep 'swaylock -f -c 4E6F6F'"
  "redshift -O 5000"
  "env -a batteryscript fish /home/friday/.config/scripts/battery.fish"
  "thunderbird"
]
