# Place this in ~/.config/river/planarwm.conf

window {
  force_ssd = true
}
bindings {
  none.XF86AudioMute = "shell pactl set-sink-mute @DEFAULT_SINK@ toggle"
  none.XF86AudioLowerVolume = "shell pactl set-sink-volume @DEFAULT_SINK@ -3%"
  none.XF86AudioRaiseVolume = "shell pactl set-sink-volume @DEFAULT_SINK@ +3%"
  none.XF86AudioMicMute = "shell pactl set-source-mute @DEFAULT_SOURCE@ toggle"
  none.XF86MonBrightnessDown = "shell brightnessctl set 5%-"
  none.XF86MonBrightnessUp = "shell brightnessctl set 5%+"
  none.Print = "shell grim -g \"$(slurp)\" - | wl-copy"
  shift.Print = "shell filename=~/Pictures/Screenshots/$(date +\"%F_%Hh%Mm%Ss\").png && grim \"$filename\" && wl-copy < \"$filename\""
  super.j = "next_slide"
  super.k = "prev_slide"
  super-shift.j = "moveto_next_slide"
  super-shift.k = "moveto_prev_slide"
  super.h = "prev_window"
  super.l = "next_window"
  super.n = "cycle_tiling"
  super.t = "spawn foot"
  super.r = "spawn wmenu-run -bip(｡•̀ᴗ-)✧"
  super.b = "spawn firefox"
  super-shift.b = "spawn firefox --private-window"
  super.f = "maximize"
  super-shift.f = "center_focused"
  super.grave = "close"
  super.space = "spawn qs ipc call panel toggle"
  super.0 = "shell ~/.config/scripts/randwall.sh"
  super.m = "shell swaylock -f -c 4e6f6f"
  super-shift.m = "exit"
  ctrl-super-shift.m = "shell systemctl poweroff"
  # For 1920x1080 at 1.5x, I have 1280x720
  # super.q = "view 0     0"
  # super.w = "view 0     720"
  # super.e = "view 0     1440"
  # super.a = "view 0     2160"
  # super.s = "view 0     2880"
  # super.d = "view 0     3600"
  # super.i = "view 0     4320"
  # super.o = "view 0     5040"
  # super.p = "view 0     5760"
}

startup = [
  "~/.config/scripts/randwall.sh"
]
