#!/bin/sh

iDIR="$HOME/.config/waybar/icons"

# Get brightness
get_backlight() {
	#LIGHT=$(printf "%s\n" $(brightness g))
	echo "$(brightnessctl -m i | cut -d',' -f4)"
}

# Get icons
get_icon() {
	backlight="$(brightnessctl g)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "19200") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "19200") && ("$current" -le "38400") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "38400") && ("$current" -le "57600") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "57600") && ("$current" -le "76800") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "76800") && ("$current" -le "96000") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(brightnessctl -m i | cut -d',' -f4)"
}

# Increase brightness
inc_backlight() {
	brightnessctl set "$1%+" && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl set "$1%-" && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight $2
elif [[ "$1" == "--dec" ]]; then
	dec_backlight $2
else
	get_backlight
fi
